### ISSUE TITLE
websockets.exceptions.ConnectionClosedError: no close frame received or sent

### ISSUE THREAD

**Issue by H4K0N42** [tintin10q/headless-henk#24]
Every 2 minutes I get this error:
![image](https://github.com/tintin10q/headless-henk/assets/78751562/cf57108d-752d-486f-bb17-8326eef3031b)

Is it an error on my side or an error In the code?

**Comment by nilsbebelaar** [comment]
headless-henk doesn't handle a server restart correctly (yet)
So just give it a restart, it should start working again.
