### ISSUE TITLE
Detect if banned or ratelimited when placing pixel

### ISSUE THREAD

**Issue by ebosveld** [tintin10q/headless-henk#30]
We checken nu bij het plaatsen van een pixel of we 200 terugkrijgen. Alleen is Reddit gemeen, want ze sturen ook 200 terug als we ratelimited of banned zijn. We zouden in de response moeten kijken of er een `errors` object is en welke message erin staat. Ik merk alleen dat mijn Python skills hiervoor even ontbreken.

```
{
   "errors":[
      {
         "message":"Ratelimited",
         "path":[
            "act"
         ],
         "extensions":{
            "nextAvailablePixelTs":2147483647000
         }
      },
      {
         "message":"ratelimit ''hit, next available: 2147483647000",
         "path":[
            "act"
         ]
      }
   ],
   "data":null
}
```

**Comment by tintin10q** [comment]
ok ja goed idee
maar wat gaan we doen dan. Die client uitzetten?

**Comment by ebosveld** [comment]
Ja, denk het wel. Want blijven retryen heeft geen zin. Die timestamp zegt iets van 2038 ofzo xD

**Comment by ebosveld** [comment]
En misschien loggen in een file, zodat je die accounts kunt weggooien

**Comment by tintin10q** [comment]
Dit is toegevoegd
